### ISSUE TITLE
Param mapping error

### ISSUE THREAD

**Issue by mshoaibdev** [lionix-team/seo-manager#1]
Hi, there is an error when using param mapping, I think it does not fetch the models list and expects some params, the dynamic url is /{{slug}}
`
    "message": "Too few arguments to function Illuminate\\Foundation\\Console\\Kernel::__construct(), 0 passed in \vendor\\lionix\\seo-manager\\src\\Traits\\SeoManagerTrait.php on line 116 and exactly 2 expected",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php",
    "line": 80,
    "trace": [
        {
            "file": "\vendor\\lionix\\seo-manager\\src\\Traits\\SeoManagerTrait.php",
            "line": 116,
            "function": "__construct",
            "class": "Illuminate\\Foundation\\Console\\Kernel",
            "type": "->"
        },`

**Comment by karakhanyans** [comment]
Hii @mshoaibdev 
Thanks for your report. 
Actually, it's not an issue, you just have to specify your models path in seo-manager.php config file, there is an option "models_path" which is empty by default.
For me models_path is "Models" and it works correctly. 
 But you have given me an idea, maybe I have to remove that option and try to get all models from the project without any configs.

**Comment by karakhanyans** [comment]
@mshoaibdev 
I've checked it, when you leave models_path config empty and want to load models from Laravels defaul app/ path it's not working, you are correct. 
Fixing that now.

**Comment by karakhanyans** [comment]
Issue is fixed.

**Comment by mshoaibdev** [comment]
I was using Laravel default model directory, by the way, it is an awesome package and thanks for the fixing.
