### ISSUE TITLE
Unknown facade Input

### ISSUE THREAD

**Issue by yura1106** [lionix-team/seo-manager#10]
In Laravel 6.x
Error: 
Class 'Illuminate\Support\Facades\Input' not found

**Comment by axtg** [comment]
Change the __construct method in /src/Controllers/ManagerController.php to:

```
    public function __construct(Request $request)
    {
        if($request->locale){
            app()->setLocale($request->locale);
            $this->locale = app()->getLocale();
        }
    }
```

And then you can delete the \Input reference at the top.

**Comment by karakhanyans** [comment]
@yura1106 thanks for response.
