### ISSUE TITLE
laravel 7 not working

### ISSUE THREAD

**Issue by guddu-patel** [lionix-team/seo-manager#14]
Hello,
I was trying to use your library in my laravel 7 project but its not supported ...
Can i get any help how i can use this in laravel 7 
![Screenshot from 2020-06-03 15-47-42](https://user-images.githubusercontent.com/17120122/83623876-9e309580-a5b1-11ea-8fda-44678201b364.png)

**Comment by sagarkhatri18** [comment]
Exactly got same issue while trying to install in Laravel 7.14.1. Please someone help me in this issue.

![image](https://user-images.githubusercontent.com/20171391/83624750-bbb22f00-a5b2-11ea-99a1-68b843bb7565.png)

**Comment by karakhanyans** [comment]
@guddu-patel @sagarkhatri18 Laravel 7 support just added. 
Please try.

**Comment by sagarkhatri18** [comment]
@karakhanyans Sir i am just working on it but same issue

**Comment by karakhanyans** [comment]
@sagarkhatri18 I've just tried on my Laravel 7 project and it's installed successfully. 
Can you please remove your composer.lock file and try again? I think it's saved some cache there.

**Comment by sagarkhatri18** [comment]
@karakhanyans Got this issue while installing. Can you please help in this issue, cannot finished installing.

![image](https://user-images.githubusercontent.com/20171391/83628450-329df680-a5b8-11ea-8057-cc12cb14e6e1.png)

**Comment by karakhanyans** [comment]
You need to run: 
php artisan vendor:publish --provider="Lionix\SeoManager\SeoManagerServiceProvider" --tag=config --force

and

php artisan vendor:publish --provider="Lionix\SeoManager\SeoManagerServiceProvider" --tag=assets --force

**Comment by sagarkhatri18** [comment]
@karakhanyans Hello thanks for your response. But now whenever i try do any operation like mapping, set title, or try lo load model columns etc. at your end i got this token mismatch issue. I set token at blade and too bootstrap.js file. Please can you help me here?

![image](https://user-images.githubusercontent.com/20171391/83633621-f753f580-a5c0-11ea-8a12-540329c3e3b5.png)
