### ISSUE TITLE
CSRF token issue in Seo-manager

### ISSUE THREAD

**Issue by guddu-patel** [lionix-team/seo-manager#15]
Thanks for your timely replay...
I am getting a error of csrf token mismatch in all the form of seo-manager.
I already spend a day still no chance
![Screenshot from 2020-06-04 11-41-24](https://user-images.githubusercontent.com/17120122/83720580-09817280-a659-11ea-91bb-3138891e4336.png)

**Comment by robertvanlienden** [comment]
I'm digging into it, looks like the CSRF token is missing in the vue requests...

I hope I got some time to fix this issue. It's my first PR if I succeed so maby it takes some time.

Keep you updated :-).

**Comment by robertvanlienden** [comment]
Right now stuck at getting NPM working on this project... It looks like there is no easy way to start developing on the Vue side? Or am I missing something.

Update; Right now got this project working! Needed to add this to the webpack.mix.js:

For editting/testing:
`mix.js('vendor/lionix/seo-manager/src/vue/seo-manager.app.js', 'public/vendor/lionix/js');`

To put it in the vendor (where I located this project)
`mix.js('vendor/lionix/seo-manager/src/vue/seo-manager.app.js', 'vendor/lionix/seo-manager/src/assets/js');`

Update; Right now I updated some title! Keep you updated, tomorrow I think I fixed this issue :-)

**Comment by robertvanlienden** [comment]
@karakhanyans Fixed lots of bugs. Some still existing, but core functionality is still working.

Can I maby get permissions to open a PR? Then I will push my updated to this repo.

Already thnx!

**Comment by karakhanyans** [comment]
Hi @robertvl 
You can push your changes to a separate branch and create pull request from there, I will review it and merge to the master branch. Thanks for your help with this.

**Comment by robertvanlienden** [comment]
> Hi @robertvl
> You can push your changes to a separate branch and create pull request from there, I will review it and merge to the master branch. Thanks for your help with this.

@karakhanyans Think something went wrong. Got this error message when trying to push my branch;
`remote: Permission to lionix-team/seo-manager.git denied to robertvl.
fatal: unable to access 'https://github.com/lionix-team/seo-manager.git/': The requested URL returned error: 403`

Trying to push a branch named `fix/csrf-token-issue`. If I got the right permissions I will open my PR :-).

Ps. Becouse NPM had some issues when I tried to build to the vendor/lionix/seo-manager/assets/js folder, I just copy-pasted the seo-manager.app.js from my public/assets/lionix/js folder. It seems like everything is working :-).

After my PR is open and merged, I will open some new issues for the bugs that are still exist.

**Comment by karakhanyans** [comment]
@robertvl this is how you should contribute to this package if you want to push your changes.
https://kbroman.org/github_tutorial/pages/fork.html

**Comment by robertvanlienden** [comment]
> @robertvl this is how you should contribute to this package if you want to push your changes.
> https://kbroman.org/github_tutorial/pages/fork.html

Thanks. Will try this afternoon (AMS time). Keep you updated.

**Comment by robertvanlienden** [comment]
Right now most of the CSRF issues are fixed and merged into master.

Think this issue can get closed. If anyone finds another CSRF bugs, feel free to make a new issue :-). 

@karakhanyans Maby make a new tagged release (1.3.4?) for this fixes?

**Comment by karakhanyans** [comment]
Thanks @robertvl 
Will make release and close the issue.
