### ISSUE TITLE
array_merge(): Expected parameter 2 to be an array, null given on seo-manager\src\routes\seo-manager.php:3

### ISSUE THREAD

**Issue by ghost** [lionix-team/seo-manager#16]
i am getting this error while installing package ...? 

 ErrorException  : array_merge(): Expected parameter 2 to be an array, null given

  at E:\xampp\htdocs\Personal\brandzshop\vendor\lionix\seo-manager\src\routes\seo-manager.php:3
    1| <?php
    2| $web = ['web'];
  > 3| $middleware = array_merge($web, config('seo-manager.middleware'));
    4| Route::group([
    5|     'middleware' => $middleware,
    6|     'prefix' => config('seo-manager.route'),
    7|     'as' => 'seo-manager.',
    8|     'namespace' => 'Lionix\SeoManager'
    9| ], function () {

  Exception trace:

  1   array_merge()
      E:\xampp\htdocs\Personal\brandzshop\vendor\lionix\seo-manager\src\routes\seo-manager.php:3

  2   require("E:\xampp\htdocs\Personal\brandzshop\vendor\lionix\seo-manager\src\routes\seo-manager.php")
      E:\xampp\htdocs\Personal\brandzshop\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php:78

  Please use the argument -v to see more details.
PS E:\xampp\htdocs\Personal\brandzshop> php artisan vendor:publish --provider="Lionix\SeoManager\SeoManagerServiceProvider" --tag=assets --force                                                                                                
   ErrorException  : array_merge(): Expected parameter 2 to be an array, null given

  at E:\xampp\htdocs\Personal\brandzshop\vendor\lionix\seo-manager\src\routes\seo-manager.php:3
    1| <?php
    2| $web = ['web'];
  > 3| $middleware = array_merge($web, config('seo-manager.middleware'));
    4| Route::group([
    5|     'middleware' => $middleware,
    6|     'prefix' => config('seo-manager.route'),
    7|     'as' => 'seo-manager.',
    8|     'namespace' => 'Lionix\SeoManager'
    9| ], function () {

  Exception trace:

  1   array_merge()
      E:\xampp\htdocs\Personal\brandzshop\vendor\lionix\seo-manager\src\routes\seo-manager.php:3

  2   require("E:\xampp\htdocs\Personal\brandzshop\vendor\lionix\seo-manager\src\routes\seo-manager.php")
      E:\xampp\htdocs\Personal\brandzshop\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php:78

  Please use the argument -v to see more details.

**Comment by karakhanyans** [comment]
Hi @Sahir-SQ 
Sorry for late reply, you need to publish package config files as described in the doc.
`php artisan vendor:publish --provider="Lionix\SeoManager\SeoManagerServiceProvider" --tag=config --force`
`php artisan vendor:publish --provider="Lionix\SeoManager\SeoManagerServiceProvider" --tag=assets --force`

**Comment by ghost** [comment]
thank you i solved it <3

**Comment by developman-akl** [comment]
> thank you i solved it <3

Could you please share how?
