### ISSUE TITLE
SeoManager object error when seoManager variable is null

### ISSUE THREAD

**Issue by mshoaibdev** [lionix-team/seo-manager#2]
When you don't have any data in SeoManger table for the current URI, it throws an error of the object, because it is null, for that you need to just check if it is empty just return a blank string. I don't know how to submit the PR.

to fixed the problem just add this after $metaData = [];
if(empty($seoManager)){
            return '';
}

**Comment by karakhanyans** [comment]
@mshoaibdev 
Thanks for your response.
The issue is fixed.

**Comment by tomphilpotts** [comment]
I was getting a similar error too. 

`"Call to a member function uri() on null"`

Added this check 


```
private function getMetaData($property) {

    {

        $route = \Route::current();

        /*
         * Add this check, I was getting an error "Call to a member function uri() on null"
         * This was because it is a 404 page.
         */
        if (empty($route)) {
	        return "Error";
        }

	    $uri = $route->uri();

        $seoManager = SeoManager::where('uri', $uri)->first();
        if(is_null($seoManager)){
            return null;
        }
 //............
}
```

Seems to have fixed the issue.
