### ISSUE TITLE
Help in understanding how it works?

### ISSUE THREAD

**Issue by web-vitality** [lionix-team/seo-manager#21]
Hey. I cannot understand why when I do set params mapping "Find By:" is not shown.
I have a route `Route::get('post/{slug}', 'PostController@index')->name('post');`,
I have a model for an example called Post.
I see my route in SEO manager, I click on edit, I see my model and all other fields are empty.
Tell me what I'm doing wrong. Thanks for any help :)
![image](https://user-images.githubusercontent.com/29637635/91212303-b0395480-e718-11ea-8892-5dd311c700d8.png)

**Comment by karakhanyans** [comment]
Hi @web-vitality 
Let's check step-by-step
Do you have your Post table migrations run in the DB? Because to fetch the columns we are using database directly.

**Comment by web-vitality** [comment]
> Hi @web-vitality
> Let's check step-by-step
> Do you have your Post table migrations run in the DB? Because to fetch the columns we are using database directly.

yes there is a posts table in the database

**Comment by web-vitality** [comment]
I forgot to send what I have to my console
![image](https://user-images.githubusercontent.com/29637635/91759039-a95b8780-ebd9-11ea-855c-3441e391e739.png)

**Comment by web-vitality** [comment]
As I understand it, this package changes the meta tags by the name of a specific route, but not by the entry of every single post that can be called by the name of that route?

**Comment by karakhanyans** [comment]
Fixed.
