### ISSUE TITLE
Invalid route action: [Lionix\SeoManager\ImportController].

### ISSUE THREAD

**Issue by DeepQservices** [lionix-team/seo-manager#24]
Invalid route action: [Lionix\SeoManager\ImportController].

**Comment by rashidul-hasan** [comment]
Anyone got any leads for this issue?

**Comment by DeepQservices** [comment]
> Anyone got any leads for this issue?

no

**Comment by karakhanyans** [comment]
@DeepQservices @rashidul-hasan did you followed the doc and published all configs? 
If no, please do and try again.

**Comment by DeepQservices** [comment]
> @DeepQservices @rashidul-hasan did you followed the doc and published all configs?
> If no, please do and try again.

@karakhanyans i have followed the doc and published all configs.
but i face this issue in laravel 6  project same error comes again and again

**Comment by kefivitch** [comment]
i'm facing the same problem and you can check #25

**Comment by kefivitch** [comment]
you can change the namespaces of the controllers and don't forget to change the namespace parameters in the vendor\lionix\seo-manager\src\routes\seo-manager.php

**Comment by karakhanyans** [comment]
@DeepQservices @rashidul-hasan @kefivitch @axtg the issue is fixed. 
Thanks, @kefivitch for the suggestion!

**Comment by karakhanyans** [comment]
Please upgrade to v1.4.1

**Comment by kefivitch** [comment]
It is my pleasure to contribute in such an amazing package !
