### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by prappo** [lionix-team/seo-manager#4]
When trying to add this package using this command 
` composer require lionix/seo-manager `

Got these errors 
` Problem 1
    - Conclusion: remove laravel/framework v5.8.8
    - Conclusion: don't install laravel/framework v5.8.8
    - lionix/seo-manager v1.2.0 requires illuminate/support 5.5.* || 5.6.* || 5.7.* -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].`

**Comment by haykbalasanyan1** [comment]
Thanks for your response @prappo 
Let me fix it now.

**Comment by karakhanyans** [comment]
Hi @prappo 
Thanks for your response, 
Let me fix it now.

**Comment by karakhanyans** [comment]
@prappo 
Now it works, closing the issue.
