### ISSUE TITLE
Auto redirecting to the previous page when auth middleware defined

### ISSUE THREAD

**Issue by devzakir** [lionix-team/seo-manager#7]
It is not working with auth middleware or even with any other middleware. When defining custom middleware it is showing an error auth()->user() null. But, I am already logged in. 

![image](https://user-images.githubusercontent.com/33604077/58754034-82198600-847d-11e9-9d00-78cc6c3c64e8.png)

**Comment by khizzar** [comment]
i am also facing the same issue please suggest a fix i have implemented it in the project as well.

**Comment by karakhanyans** [comment]
Issue is solved.
