### ISSUE TITLE
Backend fatal error

### ISSUE THREAD

**Issue by awolad** [lionix-team/seo-manager#8]
Backend fatal error: PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Call to a member function uri() on null in /home/user/project/vendor/lionix/seo-manager/src/Traits/SeoManagerTrait.php:199\nStack trace:\n#0 /home/user/project/vendor/lionix/seo-manager/src/SeoManager.php(24): Lionix\\SeoManager\\SeoManager->getMetaData('')\n#1 

/home/user/project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Lionix\\SeoManager\\SeoManager->metaData('')\n#2 /home/user/project/vendor/lionix/seo-manager/src/helpers/helpers.php(8): Illuminate\\Support\\Facades\\Facade::__callStatic('metaData', Array)\n#3 

/home/user/project/vendor/lionix/seo-manager/src/SeoManagerServiceProvider.php(82): metaData('')\n#4 [internal function]: Lionix\\SeoManager\\SeoManagerServiceProvider->Lionix\\SeoManager\\{closure}('')\n#5 

/home/user/project/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(347): call_user_func(Object(Closure), '')\n#6 /home/user in /home/user/project/vendor/lionix/seo-manager/src/Traits/SeoManagerTrait.php on line 199\n, referer: http://www.mywebsite.com

**Comment by karakhanyans** [comment]
Issue is solved.
